name: Bump flake.lock

on:
  schedule:
    - cron: "0 6 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: protected
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@fd24c48048070c1be9acd18c9d369a83f0fe94d7 # v31

      - uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd # v0.9.1
        with:
          ssh-private-key: |
            ${{ secrets.PRIVATE_NIX_KEY }}
            ${{ secrets.SECRETS_NIX_KEY }}

      - run: nix flake update

      - uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7
        with:
          commit_message: Bump flake.lock
          branch: main
          commit_options: '--no-verify --signoff'
          file_pattern: flake.lock
          commit_user_name: Flake Bot # defaults to "GitHub Actions"
          commit_author: Flake Bot <actions@github.com> # defaults to author of the commit that triggered the run
          skip_dirty_check: false
          skip_fetch: true
